import localFont from "next/font/local";
import "./globals.css";
import { BookingProvider } from "@/contexts/BookingContext";
import { SearchProvider } from "@/contexts/SearchContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AirBnB",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body
        className="bg-gray-50"
      >
        <SearchProvider>
          <BookingProvider>
            {modal}
            {children}
          </BookingProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
