import localFont from "next/font/local";
import { Fraunces } from "next/font/google";
import "./globals.css";
import { BookingProvider } from "@/contexts/BookingContext";
import Providers from "@/components/Providers";
import { auth } from "@/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "AirBnB",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, modal }) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable}`}
    >
      <body className="bg-cream font-sans text-ink">
        <Providers session={session}>
          <BookingProvider>
            {modal}
            {children}
          </BookingProvider>
        </Providers>
      </body>
    </html>
  );
}
